#KNN


In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("./Datasets/User_Data.csv")
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [6]:
df.corr()

C:\Users\arsha\AppData\Local\Temp\ipykernel_11164\1134722465.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()


User ID       Age  EstimatedSalary  Purchased
User ID          1.000000 -0.000721         0.071097   0.007120
Age             -0.000721  1.000000         0.155238   0.622454
EstimatedSalary  0.071097  0.155238         1.000000   0.362083
Purchased        0.007120  0.622454         0.362083   1.000000

In [4]:
#spliting the data
from sklearn.model_selection import train_test_split

x = df.iloc[:,[2,3]].values
y = df.iloc[:,-1].values
print(x,y)

[[    19  19000]
 [    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]
 [    26  80000]
 [    26  52000]
 [    20  86000]
 [    32  18000]
 [    18  82000]
 [    29  80000]
 [    47  25000]
 [    45  26000]
 [    46  28000]
 [    48  29000]
 [    45  22000]
 [    47  49000]
 [    48  41000]
 [    45  22000]
 [    46  23000]
 [    47  20000]
 [    49  28000]
 [    47  30000]
 [    29  43000]
 [    31  18000]
 [    31  74000]
 [    27 137000]
 [    21  16000]
 [    28  44000]
 [    27  90000]
 [    35  27000]
 [    33  28000]
 [    30  49000]
 [    26  72000]
 [    27  31000]
 [    27  17000]
 [    33  51000]
 [    35 108000]
 [    30  15000]
 [    28  84000]
 [    23  20000]
 [    25  79000]
 [    27  54000]
 [    30 135000]
 [    31  89000]
 [    24  32000]
 [    18  44000]
 [    29  83000]
 [    35  23000]
 [    27  58000]
 [    24  55000]
 [    23  48000]
 [    28  79000]
 [    22  1800

In [7]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size = .2)

print(x_train, x_test)

[[    55  39000]
 [    42  75000]
 [    37  71000]
 [    35  60000]
 [    41  72000]
 [    37  80000]
 [    55 125000]
 [    35  53000]
 [    59 130000]
 [    47  25000]
 [    49  39000]
 [    35  39000]
 [    47  20000]
 [    35  27000]
 [    32 135000]
 [    40  75000]
 [    44 139000]
 [    26  86000]
 [    26  43000]
 [    57  26000]
 [    52  38000]
 [    30 116000]
 [    26  32000]
 [    30  89000]
 [    58  38000]
 [    28  37000]
 [    37  93000]
 [    39  42000]
 [    21  72000]
 [    36  33000]
 [    58 144000]
 [    40  61000]
 [    24  19000]
 [    37  77000]
 [    35  71000]
 [    56 104000]
 [    26  15000]
 [    33  41000]
 [    48 134000]
 [    36 125000]
 [    47  34000]
 [    40 107000]
 [    53  72000]
 [    43 112000]
 [    53 143000]
 [    27  57000]
 [    27  54000]
 [    38  61000]
 [    24  58000]
 [    33 113000]
 [    35  88000]
 [    42  70000]
 [    34 115000]
 [    30  17000]
 [    41  52000]
 [    26  80000]
 [    45  22000]
 [    28  55000]
 [    26  1700

In [9]:
#feature Scaling
from sklearn.preprocessing import StandardScaler

st = StandardScaler()

x_train = st.fit_transform(x_train)
x_test = st.fit_transform(x_test)

print(x_train , x_test)

[[ 1.59561806 -0.88456714]
 [ 0.37048496  0.17010202]
 [-0.10072008  0.05291656]
 [-0.28920209 -0.26934346]
 [ 0.27624395  0.08221293]
 [-0.10072008  0.31658385]
 [ 1.59561806  1.6349203 ]
 [-0.28920209 -0.47441802]
 [ 1.97258209  1.78140213]
 [ 0.84169    -1.29471626]
 [ 1.03017201 -0.88456714]
 [-0.28920209 -0.88456714]
 [ 0.84169    -1.44119809]
 [-0.28920209 -1.23612353]
 [-0.57192511  1.92788396]
 [ 0.18200295  0.17010202]
 [ 0.55896698  2.04506942]
 [-1.13737116  0.49236204]
 [-1.13737116 -0.76738168]
 [ 1.78410007 -1.26541989]
 [ 1.31289503 -0.9138635 ]
 [-0.76040713  1.37125301]
 [-1.13737116 -1.0896417 ]
 [-0.76040713  0.58025114]
 [ 1.87834108 -0.9138635 ]
 [-0.94888914 -0.94315987]
 [-0.10072008  0.6974366 ]
 [ 0.08776194 -0.79667804]
 [-1.6085762   0.08221293]
 [-0.19496108 -1.06034533]
 [ 1.87834108  2.19155125]
 [ 0.18200295 -0.2400471 ]
 [-1.32585317 -1.47049445]
 [-0.10072008  0.22869475]
 [-0.28920209  0.05291656]
 [ 1.68985906  1.01969663]
 [-1.13737116 -1.58767991]
 

In [10]:
#importing KNN from sklearn
from sklearn.neighbors import KNeighborsClassifier

cl = KNeighborsClassifier()
cl.fit(x_train , y_train)

KNeighborsClassifier()

In [11]:
y_pred = cl.predict(x_test)

In [15]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred, labels=[0,1])
cm


array([[50,  4],
       [ 5, 21]], dtype=int64)

In [16]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_test, y_pred)
score

0.8875