In [9]:
pip install numpy

You should consider upgrading via the 'c:\Program Files\Python310\python.exe -m pip install --upgrade pip' command.


0D & 1D Array

In [2]:
import numpy as np

li = [1,2,3,4,5,6]
ar = np.array(li)
print(ar)
type(ar)

[1 2 3 4 5 6]


numpy.ndarray

2D Array

In [13]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
type(b)

[[1 2 3]
 [4 5 6]]


numpy.ndarray

3D Array

In [16]:
c = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(c)
print(type(c))
c.ndim

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>


3

Reshape

In [26]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print("The dimension is ",arr.ndim)
rearr = arr.reshape(3,4)
print(rearr)
print("The dimension is ",rearr.ndim)

The dimension is  1
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
The dimension is  2


Flattening

In [30]:
#Flattening means converting multidimensional array into 1D array
c = np.array([[1,2,3,4,5,6],[0,9,8,7,6,5]])


In [32]:
print(c.shape)

(2, 6)


In [33]:
reshaped_c = c.reshape(-1) 
print(reshaped_c)

[1 2 3 4 5 6 0 9 8 7 6 5]


*Indexing In Arrays*

In [4]:
ar = np.array([1,2,3,4,5,6,7,8,9,0])
print(ar[6])

7


In [6]:
Arr = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(Arr)
print(Arr[1,1])

[[1 2 3 4 5]
 [6 7 8 9 0]]
7


Iterating in 2D array

In [8]:
for i in Arr:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9
0


#Slicing

In [14]:
a = np.array([1,2,3,32,43,12,54,3])
print(a[2:6])
print(a[:6])
print(a[5:])
print(a[1:7:3])

print(a[::-1])

[ 3 32 43 12]
[ 1  2  3 32 43 12]
[12 54  3]
[ 2 43]
[ 3 54 12 43 32  3  2  1]


Searching

In [3]:
#randint(start,end,size) start & end represents range
a = np.random.randint(1,10,10)
print(a)
print(np.where(a == 8))
print(np.sort(a))
print(-np.sort(-a)) # or print(np.sort(a))[::-1]  #to reverse an array

[9 3 3 4 4 3 3 9 3 4]
(array([], dtype=int64),)
[3 3 3 3 3 4 4 4 9 9]
[9 9 4 4 4 3 3 3 3 3]
